name: game
description: "My great game"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flame: ^1.30.1
  google_fonts: ^6.3.0
  typled: ^0.0.4
  flame_juice_box:
    git:
      url: https://github.com/erickzanardo/flame_juice_box.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/google_fonts/Press_Start_2P/

